name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Compile CDS model
        run: npx -y @sap/cds-dk cds compile srv
      - name: CDS build
        run: npx -y @sap/cds-dk cds build